Introduction

**Introduce the project, your approach, talk about the process of how you came up with the metric and some alternatives you may have explored.**

*these are vairbales from said dataset to show what is being factored in before analyzing

In [6]:
import pandas as pd
edu = pd.read_csv("edu.csv", index_col = "Neighborhood")
edu.head(10)
for col in edu.columns:
    print(col)

Id
Estimate; Total:
Margin of Error; Total:
Estimate; Total: - No schooling completed
Margin of Error; Total: - No schooling completed
Estimate; Total: - Nursery school
Margin of Error; Total: - Nursery school
Estimate; Total: - Kindergarten
Margin of Error; Total: - Kindergarten
Estimate; Total: - 1st grade
Margin of Error; Total: - 1st grade
Estimate; Total: - 2nd grade
Margin of Error; Total: - 2nd grade
Estimate; Total: - 3rd grade
Margin of Error; Total: - 3rd grade
Estimate; Total: - 4th grade
Margin of Error; Total: - 4th grade
Estimate; Total: - 5th grade
Margin of Error; Total: - 5th grade
Estimate; Total: - 6th grade
Margin of Error; Total: - 6th grade
Estimate; Total: - 7th grade
Margin of Error; Total: - 7th grade
Estimate; Total: - 8th grade
Margin of Error; Total: - 8th grade
Estimate; Total: - 9th grade
Margin of Error; Total: - 9th grade
Estimate; Total: - 10th grade
Margin of Error; Total: - 10th grade
Estimate; Total: - 11th grade
Margin of Error; Total: - 11th grade
Estimate; Total: - 12th grade, no diploma
Margin of Error; Total: - 12th grade, no diploma
Estimate; Total: - Regular high school diploma
Margin of Error; Total: - Regular high school diploma
Estimate; Total: - GED or alternative credential
Margin of Error; Total: - GED or alternative credential
Estimate; Total: - Some college, less than 1 year
Margin of Error; Total: - Some college, less than 1 year
Estimate; Total: - Some college, 1 or more years, no degree
Margin of Error; Total: - Some college, 1 or more years, no degree
Estimate; Total: - Associate's degree
Margin of Error; Total: - Associate's degree
Estimate; Total: - Bachelor's degree
Margin of Error; Total: - Bachelor's degree
Estimate; Total: - Master's degree
Margin of Error; Total: - Master's degree
Estimate; Total: - Professional school degree
Margin of Error; Total: - Professional school degree
Estimate; Total: - Doctorate degree
Margin of Error; Total: - Doctorate degree

In [7]:
edu = pd.read_csv("edu.csv", index_col = "Neighborhood")
edu.head(10)

,Id,Estimate; Total:,Margin of Error; Total:,Estimate; Total: - No schooling completed,Margin of Error; Total: - No schooling completed,Estimate; Total: - Nursery school,Margin of Error; Total: - Nursery school,Estimate; Total: - Kindergarten,Margin of Error; Total: - Kindergarten,Estimate; Total: - 1st grade,...,Estimate; Total: - Associate's degree,Margin of Error; Total: - Associate's degree,Estimate; Total: - Bachelor's degree,Margin of Error; Total: - Bachelor's degree,Estimate; Total: - Master's degree,Margin of Error; Total: - Master's degree,Estimate; Total: - Professional school degree,Margin of Error; Total: - Professional school degree,Estimate; Total: - Doctorate degree,Margin of Error; Total: - Doctorate degree
Neighborhood,,,,,,,,,,,,,,,,,,,,,
Allegheny Center,1,791.0,140.000000,7.0,11.000000,0.0,10.000000,0.0,10.000000,0.0,...,53.0,38.000000,176.0,73.000000,74.0,66.000000,88.0,50.000000,6.0,9.000000
Allegheny West,2,283.0,92.000000,0.0,10.000000,0.0,10.000000,0.0,10.000000,0.0,...,25.0,19.000000,121.0,61.000000,12.0,13.000000,13.0,16.000000,6.0,9.000000
Allentown,3,1611.0,247.786198,14.0,24.494897,0.0,17.320508,0.0,17.320508,6.0,...,59.0,43.046487,72.0,50.049975,38.0,28.635642,30.0,29.748950,0.0,17.320508
Arlington,4,1271.0,224.512806,37.0,39.560081,0.0,17.320508,0.0,17.320508,0.0,...,124.0,54.378304,84.0,46.173586,13.0,13.038405,2.0,14.696938,0.0,17.320508
Arlington Heights,5,182.0,108.000000,0.0,10.000000,0.0,10.000000,0.0,10.000000,0.0,...,0.0,10.000000,0.0,10.000000,0.0,10.000000,0.0,10.000000,0.0,10.000000
Banksville,6,3368.0,390.564975,4.0,19.078784,0.0,20.000000,0.0,20.000000,0.0,...,366.0,142.365726,718.0,193.705963,504.0,202.763409,98.0,68.410526,0.0,20.000000
Bedford Dwellings,7,674.0,88.000000,21.0,17.000000,0.0,10.000000,0.0,10.000000,0.0,...,37.0,27.000000,37.0,29.000000,0.0,10.000000,0.0,10.000000,0.0,10.000000
Beechview,8,5834.0,512.740675,111.0,107.373181,0.0,31.622777,0.0,31.622777,0.0,...,621.0,138.852440,1089.0,223.539706,293.0,98.229324,86.0,63.694584,18.0,41.036569
Beltzhoover,9,1347.0,246.300629,14.0,26.457513,0.0,20.000000,0.0,20.000000,0.0,...,77.0,60.348985,50.0,33.645208,80.0,52.316345,0.0,20.000000,0.0,20.000000
Bloomfield,10,6603.0,431.270217,42.0,32.863353,0.0,31.622777,0.0,31.622777,0.0,...,450.0,134.469327,1704.0,252.713276,1072.0,185.429232,210.0,79.113842,217.0,78.460181

In [1]:
import pandas as pd
edu = pd.read_csv("edu.csv", index_col = "Neighborhood")
edu['Seventh_Below'] = edu['Estimate; Total: - Nursery school'] + edu['Estimate; Total: - Kindergarten'] + edu['Estimate; Total: - 1st grade'] + edu['Estimate; Total: - 2nd grade'] + edu['Estimate; Total: - 3rd grade'] + edu['Estimate; Total: - 4th grade'] + edu['Estimate; Total: - 5th grade'] + edu['Estimate; Total: - 6th grade'] + edu['Estimate; Total: - 7th grade']
edu = edu[['Estimate; Total: - Nursery school', 'Estimate; Total: - Kindergarten', 'Estimate; Total: - 1st grade', 'Estimate; Total: - 2nd grade', 'Estimate; Total: - 3rd grade', 'Estimate; Total: - 4th grade', 'Estimate; Total: - 5th grade', 'Estimate; Total: - 6th grade', 'Estimate; Total: - 7th grade', 'Seventh_Below']]
edu.head(10)

,Estimate; Total: - Nursery school,Estimate; Total: - Kindergarten,Estimate; Total: - 1st grade,Estimate; Total: - 2nd grade,Estimate; Total: - 3rd grade,Estimate; Total: - 4th grade,Estimate; Total: - 5th grade,Estimate; Total: - 6th grade,Estimate; Total: - 7th grade,Seventh_Below
Neighborhood,,,,,,,,,,
Allegheny Center,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
Allegheny West,0.0,0.0,0.0,0.0,0.0,0.0,0.0,13.0,0.0,13.0
Allentown,0.0,0.0,6.0,0.0,0.0,0.0,0.0,0.0,0.0,6.0
Arlington,0.0,0.0,0.0,0.0,0.0,0.0,0.0,6.0,0.0,6.0
Arlington Heights,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
Banksville,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
Bedford Dwellings,0.0,0.0,0.0,0.0,10.0,0.0,0.0,0.0,0.0,10.0
Beechview,0.0,0.0,0.0,0.0,0.0,0.0,0.0,9.0,46.0,55.0
Beltzhoover,0.0,0.0,0.0,0.0,0.0,0.0,0.0,9.0,0.0,9.0
Bloomfield,0.0,0.0,0.0,4.0,12.0,9.0,32.0,5.0,7.0,69.0

In [2]:
import pandas as pd
edu = pd.read_csv("edu.csv", index_col = "Neighborhood")
edu = edu[['Estimate; Total: - 8th grade']]
edu.head(10)

                   Estimate; Total: - 8th grade
Neighborhood
Allegheny Center                            0.0
Allegheny West                              9.0
Allentown                                  10.0
Arlington                                  25.0
Arlington Heights                           0.0
Banksville                                  7.0
Bedford Dwellings                           0.0
Beechview                                  70.0
Beltzhoover                                 0.0
Bloomfield                                 26.0

In [6]:
import pandas as pd
edu = pd.read_csv("edu.csv", index_col = "Neighborhood")
edu['eighth_highschool'] = edu['Estimate; Total: - 8th grade'] + edu['Estimate; Total: - 9th grade'] + edu['Estimate; Total: - 10th grade'] + edu['Estimate; Total: - 11th grade'] + edu['Estimate; Total: - 12th grade'] + edu['Regular high school diploma']
edu = edu[['Estimate; Total: - 8th grade', 'Estimate; Total: - 9th grade', 'Estimate; Total: - 10th grade', 'Estimate; Total: - 11th grade', 'Estimate; Total: - 12th grade', 'Regular high school diploma', 'eighth_highschool']]
edu.head(10)

KeyError: 'Estimate; Total: - 12th grade'

Here im taking each of the different categories I specifically want to group together and summing them up

In [12]:
#edu = pd.read_csv("edu.csv", index_col = "Neighborhood")
#df = pd.DataFrame(data)
#address = ['Estimate; Total: - 9th grade', 'Estimate; Total: - 10th grade', 'Estimate; Total: - 11th grade', 'Estimate; Total: - 12th grade']

edu['Seventh_Below'] = edu['Estimate; Total: - Nursery school'] + edu['Estimate; Total: - Kindergarten'] + edu['Estimate; Total: - 1st grade'] + edu['Estimate; Total: - 2nd grade'] + edu['Estimate; Total: - 3rd grade'] + edu['Estimate; Total: - 4th grade'] + edu['Estimate; Total: - 5th grade'] + edu['Estimate; Total: - 6th grade'] + edu['Estimate; Total: - 7th grade']
edu.head(15)
#edu[col]
edu['eighth'] = edu['Estimate; Total: - 8th grade']
edu['HighSchool'] = edu['Estimate; Total: - 9th grade'] + edu['Estimate; Total: - 10th grade'] + edu['Estimate; Total: - 11th grade'] + edu['Estimate; Total: - 12th grade'] + edu['Regular high school diploma']
#edu['some_edu'] = edu['Estimate; Total: - GED or alternative credential'] + edu['Estimate; Total: - Some college, less than 1 year'] + edu['Estimate; Total: - Some college, 1 or more years, no degree']
#edu['assoc'] = edu['Estimate; Total: - Associate degree']
#edu['bach_above'] = edu['Estimate; Total: - Bachelor degree'] + edu['Estimate; Total: - Master degree'] + edu['Estimate; Total: - Professional school degree'] + edu['Estimate; Total: - Doctorate degree']
#col_keep = ['id', 'total_surveyed','no_school','seventh_below', 'eighth', 'some_hs', 'hs', 'some_college', 'assoc', 'bach_above']
#col_per = ['no_school','seventh_below', 'eighth', 'some_hs', 'hs', 'some_college', 'assoc', 'bach_above'] #all col to make percentages of
#edu[new_col] = edu['seventh_below']
#edu.head(10)
#edu[col_keep]

#address = ['Estimate; Total: - Nursery school']

,Id,Estimate; Total:,Margin of Error; Total:,Estimate; Total: - No schooling completed,Margin of Error; Total: - No schooling completed,Estimate; Total: - Nursery school,Margin of Error; Total: - Nursery school,Estimate; Total: - Kindergarten,Margin of Error; Total: - Kindergarten,Estimate; Total: - 1st grade,...,Estimate; Total: - Bachelor's degree,Margin of Error; Total: - Bachelor's degree,Estimate; Total: - Master's degree,Margin of Error; Total: - Master's degree,Estimate; Total: - Professional school degree,Margin of Error; Total: - Professional school degree,Estimate; Total: - Doctorate degree,Margin of Error; Total: - Doctorate degree,seventh_below,Seventh_Below
Neighborhood,,,,,,,,,,,,,,,,,,,,,
Allegheny Center,1,791.0,140.000000,7.0,11.000000,0.0,10.000000,0.0,10.000000,0.0,...,176.0,73.000000,74.0,66.000000,88.0,50.000000,6.0,9.000000,0.0,0.0
Allegheny West,2,283.0,92.000000,0.0,10.000000,0.0,10.000000,0.0,10.000000,0.0,...,121.0,61.000000,12.0,13.000000,13.0,16.000000,6.0,9.000000,13.0,13.0
Allentown,3,1611.0,247.786198,14.0,24.494897,0.0,17.320508,0.0,17.320508,6.0,...,72.0,50.049975,38.0,28.635642,30.0,29.748950,0.0,17.320508,6.0,6.0
Arlington,4,1271.0,224.512806,37.0,39.560081,0.0,17.320508,0.0,17.320508,0.0,...,84.0,46.173586,13.0,13.038405,2.0,14.696938,0.0,17.320508,6.0,6.0
Arlington Heights,5,182.0,108.000000,0.0,10.000000,0.0,10.000000,0.0,10.000000,0.0,...,0.0,10.000000,0.0,10.000000,0.0,10.000000,0.0,10.000000,0.0,0.0
Banksville,6,3368.0,390.564975,4.0,19.078784,0.0,20.000000,0.0,20.000000,0.0,...,718.0,193.705963,504.0,202.763409,98.0,68.410526,0.0,20.000000,0.0,0.0
Bedford Dwellings,7,674.0,88.000000,21.0,17.000000,0.0,10.000000,0.0,10.000000,0.0,...,37.0,29.000000,0.0,10.000000,0.0,10.000000,0.0,10.000000,10.0,10.0
Beechview,8,5834.0,512.740675,111.0,107.373181,0.0,31.622777,0.0,31.622777,0.0,...,1089.0,223.539706,293.0,98.229324,86.0,63.694584,18.0,41.036569,55.0,55.0
Beltzhoover,9,1347.0,246.300629,14.0,26.457513,0.0,20.000000,0.0,20.000000,0.0,...,50.0,33.645208,80.0,52.316345,0.0,20.000000,0.0,20.000000,9.0,9.0
Bloomfield,10,6603.0,431.270217,42.0,32.863353,0.0,31.622777,0.0,31.622777,0.0,...,1704.0,252.713276,1072.0,185.429232,210.0,79.113842,217.0,78.460181,69.0,69.0
Bluff,11,1725.0,262.554756,15.0,22.737634,0.0,20.000000,0.0,20.000000,0.0,...,109.0,48.610698,45.0,37.603191,18.0,21.563859,0.0,20.000000,19.0,19.0
Bon Air,12,595.0,104.000000,8.0,12.000000,0.0,10.000000,0.0,10.000000,0.0,...,50.0,30.000000,51.0,40.000000,0.0,10.000000,9.0,15.000000,0.0,0.0
Brighton Heights,13,5389.0,360.897492,158.0,64.822835,0.0,26.457513,0.0,26.457513,0.0,...,1222.0,195.527492,405.0,104.369536,95.0,62.056426,19.0,28.618176,9.0,9.0
Brookline,14,9770.0,621.529565,45.0,45.055521,9.0,39.949969,0.0,38.729833,0.0,...,1672.0,265.825130,669.0,162.203576,117.0,76.785415,85.0,74.659226,35.0,35.0
California-Kirkbride,15,424.0,102.000000,6.0,15.000000,0.0,10.000000,0.0,10.000000,0.0,...,33.0,34.000000,18.0,18.000000,0.0,10.000000,0.0,10.000000,0.0,0.0

In [13]:
edu['eighth'] = edu['Estimate; Total: - 8th grade']
edu.head(15)

,Id,Estimate; Total:,Margin of Error; Total:,Estimate; Total: - No schooling completed,Margin of Error; Total: - No schooling completed,Estimate; Total: - Nursery school,Margin of Error; Total: - Nursery school,Estimate; Total: - Kindergarten,Margin of Error; Total: - Kindergarten,Estimate; Total: - 1st grade,...,Margin of Error; Total: - Bachelor's degree,Estimate; Total: - Master's degree,Margin of Error; Total: - Master's degree,Estimate; Total: - Professional school degree,Margin of Error; Total: - Professional school degree,Estimate; Total: - Doctorate degree,Margin of Error; Total: - Doctorate degree,seventh_below,Seventh_Below,eighth
Neighborhood,,,,,,,,,,,,,,,,,,,,,
Allegheny Center,1,791.0,140.000000,7.0,11.000000,0.0,10.000000,0.0,10.000000,0.0,...,73.000000,74.0,66.000000,88.0,50.000000,6.0,9.000000,0.0,0.0,0.0
Allegheny West,2,283.0,92.000000,0.0,10.000000,0.0,10.000000,0.0,10.000000,0.0,...,61.000000,12.0,13.000000,13.0,16.000000,6.0,9.000000,13.0,13.0,9.0
Allentown,3,1611.0,247.786198,14.0,24.494897,0.0,17.320508,0.0,17.320508,6.0,...,50.049975,38.0,28.635642,30.0,29.748950,0.0,17.320508,6.0,6.0,10.0
Arlington,4,1271.0,224.512806,37.0,39.560081,0.0,17.320508,0.0,17.320508,0.0,...,46.173586,13.0,13.038405,2.0,14.696938,0.0,17.320508,6.0,6.0,25.0
Arlington Heights,5,182.0,108.000000,0.0,10.000000,0.0,10.000000,0.0,10.000000,0.0,...,10.000000,0.0,10.000000,0.0,10.000000,0.0,10.000000,0.0,0.0,0.0
Banksville,6,3368.0,390.564975,4.0,19.078784,0.0,20.000000,0.0,20.000000,0.0,...,193.705963,504.0,202.763409,98.0,68.410526,0.0,20.000000,0.0,0.0,7.0
Bedford Dwellings,7,674.0,88.000000,21.0,17.000000,0.0,10.000000,0.0,10.000000,0.0,...,29.000000,0.0,10.000000,0.0,10.000000,0.0,10.000000,10.0,10.0,0.0
Beechview,8,5834.0,512.740675,111.0,107.373181,0.0,31.622777,0.0,31.622777,0.0,...,223.539706,293.0,98.229324,86.0,63.694584,18.0,41.036569,55.0,55.0,70.0
Beltzhoover,9,1347.0,246.300629,14.0,26.457513,0.0,20.000000,0.0,20.000000,0.0,...,33.645208,80.0,52.316345,0.0,20.000000,0.0,20.000000,9.0,9.0,0.0
Bloomfield,10,6603.0,431.270217,42.0,32.863353,0.0,31.622777,0.0,31.622777,0.0,...,252.713276,1072.0,185.429232,210.0,79.113842,217.0,78.460181,69.0,69.0,26.0
Bluff,11,1725.0,262.554756,15.0,22.737634,0.0,20.000000,0.0,20.000000,0.0,...,48.610698,45.0,37.603191,18.0,21.563859,0.0,20.000000,19.0,19.0,9.0
Bon Air,12,595.0,104.000000,8.0,12.000000,0.0,10.000000,0.0,10.000000,0.0,...,30.000000,51.0,40.000000,0.0,10.000000,9.0,15.000000,0.0,0.0,0.0
Brighton Heights,13,5389.0,360.897492,158.0,64.822835,0.0,26.457513,0.0,26.457513,0.0,...,195.527492,405.0,104.369536,95.0,62.056426,19.0,28.618176,9.0,9.0,50.0
Brookline,14,9770.0,621.529565,45.0,45.055521,9.0,39.949969,0.0,38.729833,0.0,...,265.825130,669.0,162.203576,117.0,76.785415,85.0,74.659226,35.0,35.0,106.0
California-Kirkbride,15,424.0,102.000000,6.0,15.000000,0.0,10.000000,0.0,10.000000,0.0,...,34.000000,18.0,18.000000,0.0,10.000000,0.0,10.000000,0.0,0.0,0.0

In [10]:
edu['Seventh_Below'] = edu['Estimate; Total: - Nursery school'] + edu['Estimate; Total: - Kindergarten'] + edu['Estimate; Total: - 1st grade'] + edu['Estimate; Total: - 2nd grade'] + edu['Estimate; Total: - 3rd grade'] + edu['Estimate; Total: - 4th grade'] + edu['Estimate; Total: - 5th grade'] + edu['Estimate; Total: - 6th grade'] + edu['Estimate; Total: - 7th grade']
edu.head(10)

,Id,Estimate; Total:,Margin of Error; Total:,Estimate; Total: - No schooling completed,Margin of Error; Total: - No schooling completed,Estimate; Total: - Nursery school,Margin of Error; Total: - Nursery school,Estimate; Total: - Kindergarten,Margin of Error; Total: - Kindergarten,Estimate; Total: - 1st grade,...,Estimate; Total: - Bachelor's degree,Margin of Error; Total: - Bachelor's degree,Estimate; Total: - Master's degree,Margin of Error; Total: - Master's degree,Estimate; Total: - Professional school degree,Margin of Error; Total: - Professional school degree,Estimate; Total: - Doctorate degree,Margin of Error; Total: - Doctorate degree,seventh_below,Seventh_Below
Neighborhood,,,,,,,,,,,,,,,,,,,,,
Allegheny Center,1,791.0,140.000000,7.0,11.000000,0.0,10.000000,0.0,10.000000,0.0,...,176.0,73.000000,74.0,66.000000,88.0,50.000000,6.0,9.000000,0.0,0.0
Allegheny West,2,283.0,92.000000,0.0,10.000000,0.0,10.000000,0.0,10.000000,0.0,...,121.0,61.000000,12.0,13.000000,13.0,16.000000,6.0,9.000000,13.0,13.0
Allentown,3,1611.0,247.786198,14.0,24.494897,0.0,17.320508,0.0,17.320508,6.0,...,72.0,50.049975,38.0,28.635642,30.0,29.748950,0.0,17.320508,6.0,6.0
Arlington,4,1271.0,224.512806,37.0,39.560081,0.0,17.320508,0.0,17.320508,0.0,...,84.0,46.173586,13.0,13.038405,2.0,14.696938,0.0,17.320508,6.0,6.0
Arlington Heights,5,182.0,108.000000,0.0,10.000000,0.0,10.000000,0.0,10.000000,0.0,...,0.0,10.000000,0.0,10.000000,0.0,10.000000,0.0,10.000000,0.0,0.0
Banksville,6,3368.0,390.564975,4.0,19.078784,0.0,20.000000,0.0,20.000000,0.0,...,718.0,193.705963,504.0,202.763409,98.0,68.410526,0.0,20.000000,0.0,0.0
Bedford Dwellings,7,674.0,88.000000,21.0,17.000000,0.0,10.000000,0.0,10.000000,0.0,...,37.0,29.000000,0.0,10.000000,0.0,10.000000,0.0,10.000000,10.0,10.0
Beechview,8,5834.0,512.740675,111.0,107.373181,0.0,31.622777,0.0,31.622777,0.0,...,1089.0,223.539706,293.0,98.229324,86.0,63.694584,18.0,41.036569,55.0,55.0
Beltzhoover,9,1347.0,246.300629,14.0,26.457513,0.0,20.000000,0.0,20.000000,0.0,...,50.0,33.645208,80.0,52.316345,0.0,20.000000,0.0,20.000000,9.0,9.0
Bloomfield,10,6603.0,431.270217,42.0,32.863353,0.0,31.622777,0.0,31.622777,0.0,...,1704.0,252.713276,1072.0,185.429232,210.0,79.113842,217.0,78.460181,69.0,69.0

now i layout the column of all the neighborrhoods and just the total population column

now do the total of each of the seperate categories like the totlal you found for seventh and below divided by the total population
keep doing this for each of the seperate new variables you made

now return this as a new column called percentedu_per

In [5]:
edu['seventh_below'] = edu['Estimate; Total: - Nursery school'] + edu['Estimate; Total: - Kindergarten'] + edu['Estimate; Total: - 1st grade'] + edu['Estimate; Total: - 2nd grade'] + edu['Estimate; Total: - 3rd grade'] + edu['Estimate; Total: - 4th grade'] + edu['Estimate; Total: - 5th grade'] + edu['Estimate; Total: - 6th grade'] + edu['Estimate; Total: - 7th grade'] 
#edu['eighth'] = edu['Estimate; Total: - 8th grade']
#edu['eighth'] =

col_keep = ['id', 'total_surveyed','no_school','seventh_below', 'eighth', 'some_hs', 'hs', 'some_college', 'assoc', 'bach_above']
col_per = ['no_school','seventh_below', 'eighth', 'some_hs', 'hs', 'some_college', 'assoc', 'bach_above']



#for col in col_per:
col ='seventh_below'
new_colnm = col + '_per'
print(new_colnm)
edu[new_colnm] = edu['col']
edu.head(10)

seventh_below_per

KeyError: 'col'

In [ ]:
include graph of last ten